### ISSUE TITLE
synk warnings

### ISSUE THREAD

**Issue by m4bwav** [sindresorhus/article-title#4]
I get these errors from synk when it scans article-title:
 
 ✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-LODASHMERGE-173732] in lodash.merge@4.6.0
    introduced by article-title@2.0.0 > cheerio@0.22.0 > lodash.merge@4.6.0
  This issue was fixed in versions: 4.6.2
  ✗ Prototype Pollution [Medium Severity][https://snyk.io/vuln/SNYK-JS-LODASHMERGE-173733] in lodash.merge@4.6.0
    introduced by article-title@2.0.0 > cheerio@0.22.0 > lodash.merge@4.6.0
  This issue was fixed in versions: 4.6.2

**Comment by m4bwav** [comment]
Thanks!

**Comment by m4bwav** [comment]
@sindresorhus - Snyk is still complaining about the old cheerio reference.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/article-title/releases/tag/v3.1.0
