### ISSUE TITLE
https://www.yahoo.com returns nothing

### ISSUE THREAD

**Issue by MarkRogersEx** [sindresorhus/article-title#5]
Yet when I visit the site I can see it has a title tag.
My lib (get-title-at-url) uses your lib, and [a user reported that nothing was coming out for yahoo.com](https://github.com/m4bwav/get-title-at-url/issues/3) and I tested and confirmed.

I looked at the output and verified it was empty.  I checked to make sure it was getting content back from yahoo.com and it was.  I visually scanned yahoo.com's html output and confirmed it has a title tag.  As far as I can tell its not superficially different from other sites.

For some reason the article-title doesn't like yahoo.
I know you are probably busy, but figured I would report it, since someone reported it to me.

**Comment by sindresorhus** [comment]
I have added a test that shows that it's working.

**Comment by MarkRogersEx** [comment]
allright, thanks for looking.  I'll see if I can reproduce.
